### Create Player
POST http://localhost:8080/players
Content-Type: application/json

{
  "name": "Ranger",
  "level": 2,
  "health": 90,
  "strength": 18,
  "defense": 12,
  "speed": 20
}

### Update Player
PUT http://localhost:8080/players/1
Content-Type: application/json

{
  "name": "Updated Knight",
  "level": 2,
  "health": 120,
  "strength": 25,
  "defense": 18,
  "speed": 12
}

### Create Team
POST http://localhost:8080/teams
Content-Type: application/json

{
  "name": "Red Dragons"
}

### Assign Player To Team
POST http://localhost:8080/teams/1/players/2